// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package media

// The internal/media section of the copy catalog, one constant per entry.
const (
	FrameTimeInvalid = "The input media %s has invalid keyframe timing."
	ImageIndexForm   = "image %d"
	IndexForm        = "media %d"
)
