// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package httpapi

// The internal/httpapi section of the copy catalog, one constant per entry.
const (
	ByteLimitForm     = "limit %d bytes"
	StatusExcerptForm = "%s: status %d: %s"
	TimeoutAfterForm  = "after %s"
)
