// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package kling

// The internal/provider/kling section of the copy catalog, one constant per entry.
const (
	EnvelopeCodeForm         = "%s: code %d"
	ImageTaskResponseContext = "image task response"
	ResultURLMissing         = "%s: no result url in the completed task"
	TaskIDMissing            = "%s: no task id in the creation response"
	VideoInputRejected       = "Kling models take no video input: %s"
	VideoTaskResponseContext = "video task response"
)
