package artifact

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/shdeen/bildomat/internal/errs"
	"github.com/shdeen/bildomat/internal/media"
)

// genStemPrefix starts default filenames such as bild-image and bild-video.
const genStemPrefix = "bild"

// SidecarExt is the Markdown extension shared by sidecar persistence and collision checks.
const SidecarExt = ".md"

// firstSuffixNumber is the first two-digit suffix a taken name receives.
const firstSuffixNumber = 2

// DefaultStem returns the default filename stem for an image or video run.
func DefaultStem(mediaKind media.Kind) string {
	return genStemPrefix + "-" + string(mediaKind)
}

// WriteMedia saves generated media under an available stem and returns all completed files. A
// destination failure stops further writes. It then attempts source cleanup for every supplied
// artifact, clearing each TmpPath even when removal fails.
func WriteMedia(dir, requestedStem string, mediaKind media.Kind, artifacts []Media, writesSidecar bool) (finalStem string, completedFiles []SavedFile, writeErr error) {
	if len(artifacts) == 0 {
		return "", nil, errs.ErrOutputFileEmpty
	}

	stem, firstFile, err := resolveStem(dir, requestedStem, mediaKind, artifacts, writesSidecar)
	if err != nil {
		return "", nil, errors.Join(err, Cleanup(artifacts))
	}

	savedFiles := make([]SavedFile, 0, len(artifacts))
	for artifactIndex, generated := range artifacts {
		var savedFile SavedFile
		if artifactIndex == 0 {
			savedFile, err = writeToReservedFile(firstFile, artifactPath(dir, stem, artifacts, artifactIndex), generated)
		} else {
			savedFile, err = writeArtifact(dir, artifactName(stem, artifacts, artifactIndex), generated)
		}

		writeErr = errors.Join(writeErr, err)

		if savedFile.Path == "" {
			break
		}

		savedFiles = append(savedFiles, savedFile)
	}

	return stem, savedFiles, errors.Join(writeErr, Cleanup(artifacts))
}

// writeToReservedFile writes and closes a claimed destination from generated bytes or a source
// file.
func writeToReservedFile(file *os.File, dstPath string, generated Media) (SavedFile, error) {
	if generated.TmpPath == "" {
		return commitFile(file, dstPath, generated.Data)
	}

	return copyFile(file, dstPath, generated.TmpPath)
}

// writeArtifact writes generated media under the first free filename and returns the saved file.
func writeArtifact(dir, name string, generated Media) (SavedFile, error) {
	file, path, err := claimFile(dir, name, generated.FileExt)
	if err != nil {
		return SavedFile{}, err
	}

	return writeToReservedFile(file, path, generated)
}

// suffixedName appends a numeric suffix padded to at least two digits.
func suffixedName(name string, suffixNumber int) string {
	return fmt.Sprintf("%s-%02d", name, suffixNumber)
}

// artifactName appends the artifact index to the stem for a batch and leaves a single artifact
// unnumbered.
func artifactName(stem string, artifacts []Media, i int) string {
	if len(artifacts) > 1 {
		return fmt.Sprintf("%s-%d", stem, i)
	}

	return stem
}

// artifactPath returns the destination path for an artifact, including its batch index and
// extension.
func artifactPath(dir, stem string, artifacts []Media, i int) string {
	return filepath.Join(dir, artifactName(stem, artifacts, i)+artifacts[i].FileExt)
}

// resolveStem chooses an available stem and exclusively creates its first artifact. An empty
// requested stem uses the medium's default name; collisions add a numbered suffix.
func resolveStem(dir, requestedStem string, mediaKind media.Kind, artifacts []Media, writesSidecar bool) (stem string, file *os.File, err error) {
	if requestedStem == "" {
		requestedStem = DefaultStem(mediaKind)
	}

	for {
		stem = uniqueStem(dir, requestedStem, artifacts, writesSidecar)

		claimPath := artifactPath(dir, stem, artifacts, 0)

		file, err = openFile(claimPath)
		if err == nil {
			return stem, file, nil
		}

		if !errors.Is(err, fs.ErrExist) {
			return stem, nil, errs.FileError(errs.FileOpCreate, claimPath, errs.ErrOutputFileCreate, err)
		}
	}
}

// uniqueStem returns the requested stem if every destination is free, or the first available
// numbered variant starting at 02.
func uniqueStem(dir, stem string, artifacts []Media, writesSidecar bool) string {
	if !hasDestinationClash(dir, stem, artifacts, writesSidecar) {
		return stem
	}

	for i := firstSuffixNumber; ; i++ {
		candidateStem := suffixedName(stem, i)
		if !hasDestinationClash(dir, candidateStem, artifacts, writesSidecar) {
			return candidateStem
		}
	}
}

// hasDestinationClash reports whether any exact path the run will write already exists.
func hasDestinationClash(dir, stem string, artifacts []Media, writesSidecar bool) bool {
	for artifactIndex := range artifacts {
		if fileExists(artifactPath(dir, stem, artifacts, artifactIndex)) {
			return true
		}
	}

	return writesSidecar && fileExists(filepath.Join(dir, stem+SidecarExt))
}

// fileExists reports whether a file, directory, or symbolic link occupies a path.
func fileExists(path string) bool {
	_, err := os.Lstat(path)

	return err == nil
}
