package artifact

import (
	"errors"
	"fmt"

	"github.com/shdeen/bildomat/internal/errs"
	"github.com/shdeen/bildomat/internal/media"
)

// Media contains generated media stored in memory or in a temporary file.
//   - Data: the generated bytes when held in memory
//   - TmpPath: the temporary file path when stored on disk
//   - FileExt: the detected or fallback filename extension, including its leading period
type Media struct {
	Data    []byte
	TmpPath string
	FileExt string
}

// New returns a bytes-backed artifact with an extension inferred from its MIME type, data, or
// fallback extension.
func New(data []byte, mime, fallbackExt string) (Media, error) {
	if len(data) == 0 {
		return Media{}, fmt.Errorf("%q, %w", ResponseEmptyInline, errs.ErrResponseNoData)
	}

	return Media{Data: data, FileExt: media.ExtForData(mime, data, fallbackExt)}, nil
}

// Cleanup attempts to remove every temporary source in the supplied artifacts. It clears their
// TmpPath fields even on failure and returns all removal errors.
func Cleanup(artifacts []Media) error {
	var cleanupErr error
	for artifactIndex := range artifacts {
		cleanupErr = errors.Join(cleanupErr, artifacts[artifactIndex].cleanup())
	}

	return cleanupErr
}

// cleanup attempts to remove this artifact's temporary source and clears TmpPath, even on failure.
func (generated *Media) cleanup() error {
	if generated.TmpPath == "" {
		return nil
	}

	sourcePath := generated.TmpPath
	generated.TmpPath = ""

	return removeFile(sourcePath, errs.ErrOutputFileRemove)
}
