// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package artifact

// The internal/artifact section of the copy catalog, one constant per entry.
const (
	ResponseEmptyInline = "empty inline result"
)
