// Command flagsetup generates the parameter flag records of internal/params
// from their one source document, internal/params/config/paramflags.json.
//
// It runs from the go:generate directive in internal/params/flag.go, never at
// run time, and writes internal/params/zz_paramflags.go: one function returning
// the records as a Go literal.
//
// Validation: a malformed document, content after the document, a flag ID
// declared twice, an alias declared twice, and a data type outside string,
// number, integer, and boolean all fail generation, and nothing is written.
//
// The generator imports nothing from this module. internal/params does not
// compile while its generated file is missing or broken, so a generator that
// imported it could not run to repair it. Its diagnostic constants must first
// be generated by copygen, which also imports no application package.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"os"
	"slices"
	"strings"
)

// documentPath is the parameter flag document, relative to internal/params,
// the directory the go:generate directive runs this tool in.
const documentPath = "config/paramflags.json"

// generatedName is the Go source file written into internal/params.
const generatedName = "zz_paramflags.go"

// The data types a parameter flag record may declare.
const (
	dataString  = "string"
	dataNumber  = "number"
	dataInteger = "integer"
	dataBoolean = "boolean"
)

// The generated file's fixed source fragments.
const (
	generatedHeader = "// Code generated by flagsetup from internal/params/config/paramflags.json. DO NOT EDIT.\n\n" +
		"package params\n\n" +
		"// Flags returns the parameter flag records, one per generation parameter,\n" +
		"// in the order the parameter flag document declares them. Every call builds a\n" +
		"// new slice, so no caller's change reaches another caller.\n" +
		"func Flags() []Flag {\n\treturn []Flag{\n"
	generatedFooter = "\t}\n}\n"

	recordOpening          = "\t\t{\n"
	recordClosing          = "\t\t},\n"
	identityFieldsForm     = "\t\t\tFlagID: %q,\n\t\t\tFlagName: %q,\n\t\t\tDataType: %q,\n"
	aliasesFieldForm       = "\t\t\tAliases: %#v,\n"
	descriptionFieldForm   = "\t\t\tDescription: %q,\n"
	exampleValuesFieldForm = "\t\t\tExampleValues: %#v,\n"
	commentFieldForm       = "\t\t\tComment: %q,\n"
	textHintFieldForm      = "\t\t\tTextHint: %q,\n"
	allowMultipleField     = "\t\t\tAllowMultiple: true,\n"
)

// flagRecord is one record of the parameter flag document. Its fields mirror
// the document's keys, which are also the fields of params.Flag.
//   - FlagID: the parameter's canonical flag name
//   - FlagName: the parameter name shown to users
//   - DataType: the parameter's value type
//   - Aliases: alternate flag names
//   - Description: the parameter description shown in help output
//   - ExampleValues: example values shown in help output
//   - Comment: additional parameter guidance shown in help output
//   - TextHint: the value placeholder shown in help output
//   - AllowMultiple: whether the parameter accepts multiple values
type flagRecord struct {
	FlagID        string   `json:"flagID"`
	FlagName      string   `json:"flagName"`
	DataType      string   `json:"dataType"`
	Aliases       []string `json:"aliases"`
	Description   string   `json:"description"`
	ExampleValues []string `json:"exampleValues"`
	Comment       string   `json:"comment"`
	TextHint      string   `json:"textHint"`
	AllowMultiple bool     `json:"allowMultiple"`
}

func main() {
	if err := generate(documentPath, generatedName); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// generate takes the path of the parameter flag document and the path of the
// Go source file to write, and writes the records the document declares. A
// document that does not decode or fails validation returns its
// classification error. A document that cannot be read, and generated source
// that cannot be formatted or written, return the category error wrapping the
// cause. Nothing is written on any failure.
func generate(sourcePath, targetPath string) error {
	// #nosec G304 -- sourcePath is the fixed document beside the go:generate directive, or a test's own file.
	document, err := os.ReadFile(sourcePath)
	if err != nil {
		return fmt.Errorf("%q: %w, %w", sourcePath, errParamFlags, err)
	}

	records, err := readRecords(sourcePath, document)
	if err != nil {
		return err
	}

	generated, err := format.Source([]byte(renderSource(records)))
	if err != nil {
		return fmt.Errorf("%q: %w, %w", targetPath, errParamFlags, err)
	}

	if err := os.WriteFile(targetPath, generated, 0o600); err != nil {
		return fmt.Errorf("%q: %w, %w", targetPath, errParamFlags, err)
	}

	return nil
}

// readRecords takes the path of the parameter flag document, which its errors
// name, and the document's bytes, and returns the document's records. It
// returns the decode error for a malformed document or an unknown key, the
// trailing-content error for anything after the document, and the
// invalid-content error for a flag ID declared twice, an alias declared
// twice, or an unsupported data type.
func readRecords(sourcePath string, document []byte) ([]flagRecord, error) {
	decoder := json.NewDecoder(bytes.NewReader(document))
	decoder.DisallowUnknownFields()

	var records []flagRecord
	if err := decoder.Decode(&records); err != nil {
		return nil, fmt.Errorf("%q: %w, %w", sourcePath, errParamFlagsDecode, err)
	}

	switch err := decoder.Decode(new(json.RawMessage)); {
	case err == nil:
		return nil, fmt.Errorf("%q: %w", sourcePath, errParamFlagsTrailing)
	case !errors.Is(err, io.EOF):
		return nil, fmt.Errorf("%q: %w, %w", sourcePath, errParamFlagsDecode, err)
	}

	declaredIDs := map[string]bool{}
	declaredAliases := map[string]bool{}

	for i := range records {
		record := &records[i]
		if declaredIDs[record.FlagID] {
			return nil, invalidContentError(sourcePath, FlagIDDuplicate, record.FlagID)
		}

		declaredIDs[record.FlagID] = true

		if !slices.Contains([]string{dataString, dataNumber, dataInteger, dataBoolean}, record.DataType) {
			return nil, invalidContentError(sourcePath, FlagDataTypeInvalid, record.FlagID, record.DataType)
		}

		for _, alias := range record.Aliases {
			if declaredAliases[alias] {
				return nil, invalidContentError(sourcePath, FlagAliasDuplicate, record.FlagID, alias)
			}

			declaredAliases[alias] = true
		}
	}

	return records, nil
}

// invalidContentError takes the path of the parameter flag document, the form
// of one content fault, and the fault's values, and returns the
// invalid-content error naming the document and the fault.
func invalidContentError(sourcePath, faultForm string, faultValues ...any) error {
	return fmt.Errorf("%q, %w", sourcePath+": "+fmt.Sprintf(faultForm, faultValues...), errParamFlagsInvalid)
}

// renderSource takes the records and returns the Go source of the generated
// file, before formatting. A key the document leaves out is left out of the
// record's literal, so the field keeps the zero value an absent key decodes
// to; a list the document declares empty stays an empty list.
func renderSource(records []flagRecord) string {
	var source strings.Builder

	source.WriteString(generatedHeader)

	for i := range records {
		record := &records[i]

		source.WriteString(recordOpening)
		fmt.Fprintf(&source, identityFieldsForm, record.FlagID, record.FlagName, record.DataType)

		if record.Aliases != nil {
			fmt.Fprintf(&source, aliasesFieldForm, record.Aliases)
		}

		fmt.Fprintf(&source, descriptionFieldForm, record.Description)

		if record.ExampleValues != nil {
			fmt.Fprintf(&source, exampleValuesFieldForm, record.ExampleValues)
		}

		if record.Comment != "" {
			fmt.Fprintf(&source, commentFieldForm, record.Comment)
		}

		if record.TextHint != "" {
			fmt.Fprintf(&source, textHintFieldForm, record.TextHint)
		}

		if record.AllowMultiple {
			source.WriteString(allowMultipleField)
		}

		source.WriteString(recordClosing)
	}

	source.WriteString(generatedFooter)

	return source.String()
}
