// Command flagsetup generates parameter records from internal/params/config/paramflags.json. The
// go:generate directive runs it from internal/params.
//
// It imports no application packages so it can regenerate missing or broken records. Its diagnostic
// constants must first be generated by copygen.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"os"
	"slices"
	"strings"
)

// documentPath locates the parameter flag document relative to internal/params. The go:generate
// directive runs this tool from that directory.
const documentPath = "config/paramflags.json"

// generatedName is the Go source file written into internal/params.
const generatedName = "zz_paramflags.go"

// The data types a parameter flag record may declare.
const (
	dataString  = "string"
	dataNumber  = "number"
	dataInteger = "integer"
	dataBoolean = "boolean"
)

// The generated file's fixed source fragments.
const (
	generatedHeader = "// Code generated by flagsetup from internal/params/config/paramflags.json. DO NOT EDIT.\n\n" +
		"package params\n\n" +
		"// Flags returns generation parameter records in declaration order. Each call creates independent\n" +
		"// records that callers may modify.\n" +
		"func Flags() []Flag {\n\treturn []Flag{\n"
	generatedFooter = "\t}\n}\n"

	recordOpening          = "\t\t{\n"
	recordClosing          = "\t\t},\n"
	identityFieldsForm     = "\t\t\tFlagID: %q,\n\t\t\tFlagName: %q,\n\t\t\tDataType: %q,\n"
	aliasesFieldForm       = "\t\t\tAliases: %#v,\n"
	descriptionFieldForm   = "\t\t\tDescription: %q,\n"
	exampleValuesFieldForm = "\t\t\tExampleValues: %#v,\n"
	commentFieldForm       = "\t\t\tComment: %q,\n"
	textHintFieldForm      = "\t\t\tTextHint: %q,\n"
	allowMultipleField     = "\t\t\tAllowMultiple: true,\n"
)

// flagRecord is one record of the parameter flag document. Its fields mirror the document's keys,
// which are also the fields of params.Flag.
//   - FlagID: the parameter's canonical flag name
//   - FlagName: the parameter name shown to users
//   - DataType: the parameter's value type
//   - Aliases: alternate flag names
//   - Description: the parameter description shown in help output
//   - ExampleValues: example values shown in help output
//   - Comment: additional parameter guidance shown in help output
//   - TextHint: the value placeholder shown in help output
//   - AllowMultiple: whether the parameter accepts multiple values
type flagRecord struct {
	FlagID        string   `json:"flagID"`
	FlagName      string   `json:"flagName"`
	DataType      string   `json:"dataType"`
	Aliases       []string `json:"aliases"`
	Description   string   `json:"description"`
	ExampleValues []string `json:"exampleValues"`
	Comment       string   `json:"comment"`
	TextHint      string   `json:"textHint"`
	AllowMultiple bool     `json:"allowMultiple"`
}

// main generates parameter records and reports failures on stderr with a nonzero exit status.
func main() {
	if err := generate(documentPath, generatedName); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// generate validates and formats parameter records before writing targetPath. Failures identify the
// source or target and retain their error category and cause.
func generate(sourcePath, targetPath string) error {
	// #nosec G304 -- sourcePath is the fixed document beside the go:generate directive, or a test's own file.
	document, err := os.ReadFile(sourcePath)
	if err != nil {
		return fmt.Errorf("%q: %w, %w", sourcePath, errParamFlags, err)
	}

	records, err := readRecords(sourcePath, document)
	if err != nil {
		return err
	}

	generated, err := format.Source([]byte(renderSource(records)))
	if err != nil {
		return fmt.Errorf("%q: %w, %w", targetPath, errParamFlags, err)
	}

	if err := os.WriteFile(targetPath, generated, 0o600); err != nil {
		return fmt.Errorf("%q: %w, %w", targetPath, errParamFlags, err)
	}

	return nil
}

// readRecords decodes one strict JSON document and validates IDs, aliases, and data types. Errors
// name sourcePath; duplicate IDs and duplicate aliases are checked separately.
func readRecords(sourcePath string, document []byte) ([]flagRecord, error) {
	decoder := json.NewDecoder(bytes.NewReader(document))
	decoder.DisallowUnknownFields()

	var records []flagRecord
	if err := decoder.Decode(&records); err != nil {
		return nil, fmt.Errorf("%q: %w, %w", sourcePath, errParamFlagsDecode, err)
	}

	switch err := decoder.Decode(new(json.RawMessage)); {
	case err == nil:
		return nil, fmt.Errorf("%q: %w", sourcePath, errParamFlagsTrailing)
	case !errors.Is(err, io.EOF):
		return nil, fmt.Errorf("%q: %w, %w", sourcePath, errParamFlagsDecode, err)
	}

	declaredIDs := map[string]bool{}
	declaredAliases := map[string]bool{}

	for i := range records {
		record := &records[i]
		if declaredIDs[record.FlagID] {
			return nil, invalidContentError(sourcePath, FlagIDDuplicate, record.FlagID)
		}

		declaredIDs[record.FlagID] = true

		if !slices.Contains([]string{dataString, dataNumber, dataInteger, dataBoolean}, record.DataType) {
			return nil, invalidContentError(sourcePath, FlagDataTypeInvalid, record.FlagID, record.DataType)
		}

		for _, alias := range record.Aliases {
			if declaredAliases[alias] {
				return nil, invalidContentError(sourcePath, FlagAliasDuplicate, record.FlagID, alias)
			}

			declaredAliases[alias] = true
		}
	}

	return records, nil
}

// invalidContentError classifies a content fault and includes its source path and details.
func invalidContentError(sourcePath, faultForm string, faultValues ...any) error {
	return fmt.Errorf("%q, %w", sourcePath+": "+fmt.Sprintf(faultForm, faultValues...), errParamFlagsInvalid)
}

// renderSource returns unformatted Go literals in record order and preserves string values. It
// preserves the distinction between nil slices and explicitly empty slices.
func renderSource(records []flagRecord) string {
	var source strings.Builder

	source.WriteString(generatedHeader)

	for i := range records {
		record := &records[i]

		source.WriteString(recordOpening)
		fmt.Fprintf(&source, identityFieldsForm, record.FlagID, record.FlagName, record.DataType)

		if record.Aliases != nil {
			fmt.Fprintf(&source, aliasesFieldForm, record.Aliases)
		}

		fmt.Fprintf(&source, descriptionFieldForm, record.Description)

		if record.ExampleValues != nil {
			fmt.Fprintf(&source, exampleValuesFieldForm, record.ExampleValues)
		}

		if record.Comment != "" {
			fmt.Fprintf(&source, commentFieldForm, record.Comment)
		}

		if record.TextHint != "" {
			fmt.Fprintf(&source, textHintFieldForm, record.TextHint)
		}

		if record.AllowMultiple {
			source.WriteString(allowMultipleField)
		}

		source.WriteString(recordClosing)
	}

	source.WriteString(generatedFooter)

	return source.String()
}
