// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package main

// The tools/flagsetup section of the copy catalog, one constant per entry.
const (
	FlagAliasDuplicate  = "flag %s: duplicate alias %q"
	FlagDataTypeInvalid = "flag %s: data type %q not one of string|number|integer|boolean"
	FlagIDDuplicate     = "duplicate flag ID %q"
)
