// Command copygen generates the per-package copy constants from the one
// catalog source, internal/templates/copy.toml.
//
// The catalog's top-level tables name package directories relative to the
// repository root. For each table, copygen writes <dir>/zz_consts.go:
// one Go string constant per entry, named exactly by the entry key. It runs
// from the internal/templates directory via its go:generate directive.
//
// Validation: a malformed TOML document, a table naming no package
// directory, a non-string value, or an entry key that is not a valid
// exported Go identifier all fail generation.
//
// String discipline: this tool builds the catalog, so it cannot take its own
// wording from it; its diagnostics are named constants here instead.
package main

import (
	"errors"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
)

// errCatalogEntry marks a catalog source whose shape, entry form, or target
// package is invalid.
var errCatalogEntry = errors.New("invalid catalog entry")

// sourceName is the catalog source read from the working directory.
const sourceName = "copy.toml"

// generatedName is the Go source written into each target package directory.
const generatedName = "zz_consts.go"

// The tool's diagnostics. The catalog cannot supply them: it is the
// artifact under construction.
const (
	diagPrefix           = "copygen:"
	diagReadFailed       = "reading %s: %w"
	diagWriteFailed      = "writing %s: %w"
	diagWrittenReport    = "copygen: %d constants written to %s\n"
	diagSourceNoParse    = "%s does not parse: %w"
	diagTableNotDir      = "table %s names no package directory"
	diagEntryNotTable    = "top-level entry %s is not a table; every entry lives in a [package-dir] table"
	diagKeyNotIdentifier = "entry %s in table %s is not a valid exported Go identifier"
	diagValueNotString   = "entry %s.%s is not a string"
	diagNoPackageClause  = "no package clause found in %s"
	diagFormatFailed     = "formatting the %s section failed: %w"
)

// The generated file's fixed source fragments.
const (
	generatedHeaderForm  = "// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.\n\npackage %s\n\n"
	generatedCommentForm = "// The %s section of the copy catalog, one constant per entry.\nconst (\n"
	generatedFooter      = ")\n"
)

// identifierForm is the required shape of an entry key: a valid exported
// Go identifier.
var identifierForm = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)

func main() {
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, diagPrefix, err)
		os.Exit(1)
	}
}

// generate reads and validates the catalog source and writes each package's
// generated constants file.
func generate() error {
	sourcePath, err := filepath.Abs(sourceName)
	if err != nil {
		return fmt.Errorf("%q: %w, %w", sourceName, errCatalogEntry, err)
	}

	repositoryRoot := filepath.Join(filepath.Dir(sourcePath), "..", "..")

	sections, err := loadCatalog(sourcePath, repositoryRoot)
	if err != nil {
		return err
	}

	dirs := make([]string, 0, len(sections))
	for dir := range sections {
		dirs = append(dirs, dir)
	}

	sort.Strings(dirs)

	rendered := make(map[string]string, len(dirs))
	for _, dir := range dirs {
		generated, err := renderPackageSource(repositoryRoot, dir, sections[dir])
		if err != nil {
			return err
		}

		rendered[dir] = generated
	}

	for _, dir := range dirs {
		target := filepath.Join(repositoryRoot, dir, generatedName)
		if err := os.WriteFile(target, []byte(rendered[dir]), 0o600); err != nil {
			return fmt.Errorf(diagWriteFailed, target, err)
		}

		fmt.Printf(diagWrittenReport, len(sections[dir]), target)
	}

	return nil
}

// loadCatalog decodes the catalog source into per-package entry maps,
// validating the document shape, every table, and every entry.
func loadCatalog(sourcePath, repositoryRoot string) (map[string]map[string]string, error) {
	// #nosec G304 -- sourcePath is the fixed catalog source beside the go:generate directive.
	sourceBytes, err := os.ReadFile(sourcePath)
	if err != nil {
		return nil, fmt.Errorf(diagReadFailed, sourcePath, err)
	}

	var document map[string]any
	if err := toml.Unmarshal(sourceBytes, &document); err != nil {
		return nil, fmt.Errorf(diagSourceNoParse, sourceName, err)
	}

	sections := map[string]map[string]string{}

	for tableName, tableValue := range document {
		table, ok := tableValue.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("%q, %w", fmt.Sprintf(diagEntryNotTable, tableName), errCatalogEntry)
		}

		targetInfo, statErr := os.Stat(filepath.Join(repositoryRoot, tableName))
		if statErr != nil {
			return nil, fmt.Errorf("%q, %w, %w", fmt.Sprintf(diagTableNotDir, tableName), errCatalogEntry, statErr)
		}

		if !targetInfo.IsDir() {
			return nil, fmt.Errorf("%q, %w", fmt.Sprintf(diagTableNotDir, tableName), errCatalogEntry)
		}

		entries := map[string]string{}

		for entryKey, entryValue := range table {
			if !identifierForm.MatchString(entryKey) {
				return nil, fmt.Errorf("%q, %w", fmt.Sprintf(diagKeyNotIdentifier, entryKey, tableName), errCatalogEntry)
			}

			text, ok := entryValue.(string)
			if !ok {
				return nil, fmt.Errorf("%q, %w", fmt.Sprintf(diagValueNotString, tableName, entryKey), errCatalogEntry)
			}

			entries[entryKey] = text
		}

		sections[tableName] = entries
	}

	return sections, nil
}

// renderPackageSource renders one package's generated constants file.
func renderPackageSource(repositoryRoot, dir string, entries map[string]string) (string, error) {
	packageName, err := packageNameOf(filepath.Join(repositoryRoot, dir))
	if err != nil {
		return "", err
	}

	keys := make([]string, 0, len(entries))
	for key := range entries {
		keys = append(keys, key)
	}

	sort.Strings(keys)

	var source strings.Builder

	fmt.Fprintf(&source, generatedHeaderForm, packageName)
	fmt.Fprintf(&source, generatedCommentForm, dir)

	for _, key := range keys {
		source.WriteString("\t" + key + " = " + strconv.Quote(entries[key]) + "\n")
	}

	source.WriteString(generatedFooter)

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return "", fmt.Errorf(diagFormatFailed, dir, err)
	}

	return string(formatted), nil
}

// packageNameOf returns the package clause of the first Go source file in a
// directory, skipping test files and the generated file itself.
func packageNameOf(dir string) (string, error) {
	dirEntries, err := os.ReadDir(dir)
	if err != nil {
		return "", fmt.Errorf(diagReadFailed, dir, err)
	}

	for _, dirEntry := range dirEntries {
		name := dirEntry.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == generatedName {
			continue
		}

		sourcePath := filepath.Join(dir, name)

		parsedSource, parseErr := parser.ParseFile(token.NewFileSet(), sourcePath, nil, parser.PackageClauseOnly)
		if parseErr != nil {
			return "", fmt.Errorf("%q: %w, %w", sourcePath, errCatalogEntry, parseErr)
		}

		return parsedSource.Name.Name, nil
	}

	return "", fmt.Errorf("%q, %w", fmt.Sprintf(diagNoPackageClause, dir), errCatalogEntry)
}
