// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package catalog

// The internal/catalog section of the copy catalog, one constant per entry.
const (
	AliasContextForm             = "%s alias %s"
	AllowedValueBelowCount       = "model %s, flag %s: allowed value %q below the minimum count of one"
	AllowedValueFault            = "model %s, flag %s: allowed value %s"
	ConfigMissing                = "no config section holding the request settings"
	ConfigProviderSourceMismatch = "%s: declares provider %q under the %q source"
	FrameMediaIncomplete         = "VideoAPI: incomplete frame-media description"
	ImageAPIMissing              = "no ImageAPI for the declared image medium"
	ImageFallbackExtMissing      = "AdapterAPI: no ImageFallbackExt for the declared image medium"
	InputMediaEncodingConflict   = "%s: input media encoding %q cannot use style %q"
	InputMediaParamMissing       = "%s: required input media field name is missing"
	InputMediaPayloadTypeInvalid = "%s: InputMediaPayloadType %q invalid (want json|form)"
	InputMediaStyleInvalid       = "%s: InputMediaStyle %q invalid (want parts|nested|single-or-array|string)"
	ModelFlagDuplicate           = "model %s: duplicate params entry for flag %s"
	ModelFlagFault               = "model %s, flag %s: %s"
	ModelIDMissing               = "model ID must not be empty"
	ModelMediaInvalid            = "model %s: invalid Media %q (want image|video)"
	ModelNameMissing             = "model %s: no name declared"
	ParamGuidanceMissing         = "model %s, flag %s: no allowed values, range, or size bounds declared, and the flag record has no text hint or example values"
	ParamsFlagUnknown            = "model %s: params entry flagID %q names no enumerated flag"
	PollBudgetNotPositive        = "VideoAPI: PollTimeout %d not positive"
	PollIntervalInvalid          = "%s: interval %d not positive"
	PollIntervalNotPositive      = "VideoAPI: PollInterval %d not positive"
	PollTimeoutInvalid           = "%s: timeout %d not positive"
	ProviderDefaultModelUnknown  = "provider %s: defaultModel %q names no model of the provider"
	RequestPathConflict          = "model %s: request paths %q and %q conflict"
	RequestPathInvalid           = "model %s: request path %q contains an empty segment"
	StringParamsUnknownFlag      = "StringParams: unknown flagID %q"
	VideoAPIMissing              = "no VideoAPI for the declared video medium"
	VideoFallbackExtMissing      = "AdapterAPI: no VideoFallbackExt for the declared video medium"
)
