// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package generation

// The internal/generation section of the copy catalog, one constant per entry.
const (
	FrameAnchorConflict        = "%s and %s both request the %s frame."
	FrameCountExceeded         = "%d timed inputs exceed the model's opening and closing frames."
	FrameOnVideo               = "A video input cannot take a frame prefix: %s."
	FrameTimeShared            = "%s and %s share the frame time %g."
	ReasonAdoptedFromReference = "adopted from the reference image"
	ReasonFrameTimeSnapped     = "frame time %g snapped to the %s frame"
	ReasonMatchedToRequest     = "matched to %s request"
	ReasonNoFramePrefix        = "the model does not accept a frame prefix"
	ReasonNotConsumed          = "not consumed by %s"
)
