// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package google

// The internal/provider/google section of the copy catalog, one constant per entry.
const (
	AdapterAPIMissing       = "google.json: no AdapterAPI section"
	ErrorCodeForm           = "%s: code %v: %s"
	InteractionMediaMissing = "%s: no %s in the interaction"
	ReasonReferenceImages   = "reference images"
	VeoClosingNeedsOpening  = "Veo requires an opening frame image with a closing frame image"
	VeoMediaMixed           = "Veo request mixes image and video inputs"
	VeoOneVideo             = "Veo accepts one input video"
	VeoOperationNameMissing = "%s: no operation name in the start response"
	VeoSampleBytesInvalid   = "%s: sample %d video bytes"
	VeoSampleEmpty          = "%s: sample %d carries no video data or uri"
	VeoVideoMissing         = "%s: no video in the completed operation"
)
