package main

// Invariants tested:
//  1. Recreation of an output directory: writeRunResults must recreate a missing output directory
//     and preserve the generated bytes in paid-result.png.
//  2. Sidecars after source cleanup failure: After source cleanup fails, writeRunResults must
//     preserve the completed media and attempt the requested sidecar. It must report a successful
//     sidecar or join its failure with the cleanup cause, while excluding sidecars from the
//     returned media slice.
//  3. Failed preparation records: Given an incompatible Veo source, adjustRequest must leave
//     recorded provider calls and responses empty. It must omit unprepared parameters and retain a
//     supplied resolution that was prepared before rejection.

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"testing"

	"github.com/shdeen/bildomat/internal/artifact"
	"github.com/shdeen/bildomat/internal/catalog"
	"github.com/shdeen/bildomat/internal/errs"
	"github.com/shdeen/bildomat/internal/generation"
	"github.com/shdeen/bildomat/internal/media"
	"github.com/shdeen/bildomat/internal/metadata"
	"github.com/shdeen/bildomat/internal/output"
	"github.com/shdeen/bildomat/internal/params"
)

// TestWriteRunResultsRecreatesOutputDir verifies invariant #1: Recreation of an output directory.
//
// What is being tested:
// Given a missing output directory and a generated PNG artifact, writeRunResults must recreate the
// directory and save paid-result.png containing exactly paid generation without an error.
//
// Test class: Expanded.
// Test layer: Hardening/adversarial.
func TestWriteRunResultsRecreatesOutputDir(t *testing.T) {
	app := realApp(t)

	outDir := filepath.Join(t.TempDir(), "removed", "output")
	if _, err := os.Stat(outDir); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("💣 post-generation output directory state = %v, want absent", err)
	}

	result := generation.Result{Artifacts: []artifact.Media{{
		Data:    []byte("paid generation"),
		FileExt: ".png",
	}}}

	var writeErr error

	_ = captureBoth(t, func() {
		_, _, writeErr = writeRunResults(
			&result,
			outDir,
			"paid-result",
			"",
			&generation.Generation{ProvModelPair: catalog.ProvModelPair{Model: catalog.Model{ID: "fixture-model"}}, Preparation: generation.Preparation{Params: params.Values{}}},
			app.catalog.Flags,
			&output.GenerationOutcome{},
		)
	})
	if writeErr != nil {
		t.Errorf("✗ completed generation could not be saved: %v", writeErr)
	}

	landedPath := filepath.Join(outDir, "paid-result.png")
	// #nosec G304 -- landedPath is inside this test's temporary directory.
	landedBytes, err := os.ReadFile(landedPath)
	if err != nil {
		t.Errorf("✗ generated artifact is missing from %q: %v", landedPath, err)
	} else if string(landedBytes) != "paid generation" {
		t.Errorf("✗ generated artifact content = %q, want %q", landedBytes, "paid generation")
	}

	if !t.Failed() {
		t.Log("✓ the absent resolved directory is recreated before generated bytes are saved")
	}
}

// TestSidecarAfterSourceCleanupFailure verifies invariant #2: Sidecars after source cleanup
// failure.
// Test class: Expanded.
// Test layer: Hardening/adversarial.
// What is being tested:
// When removing a temporary source returns os.ErrPermission, writeRunResults must still save its
// exact bytes and return that error plus one saved-media record. With the ordinary stem, it must
// write the thoughts to a sidecar and report its path and byte count in outcome.Artifacts. With a
// stem that makes the sidecar name too long, it must also return ENAMETOOLONG and report only the
// saved media. The returned saved-media slice must exclude the sidecar in both cases.
func TestSidecarAfterSourceCleanupFailure(t *testing.T) {
	for _, sidecarFailure := range []bool{false, true} {
		caseName := "saved sidecar"
		if sidecarFailure {
			caseName = "failed sidecar"
		}

		t.Run(caseName, func(t *testing.T) {
			sourceDirectory := t.TempDir()

			source := filepath.Join(sourceDirectory, "generated")
			if err := os.WriteFile(source, []byte("generated bytes"), 0o600); err != nil {
				t.Fatalf("💣 generated source fixture: %v", err)
			}

			// #nosec G302 -- owner directory permissions establish and restore the test failure.
			if err := os.Chmod(sourceDirectory, 0o500); err != nil {
				t.Fatalf("💣 source permissions: %v", err)
			}

			t.Cleanup(func() {
				// #nosec G302 -- owner directory permissions establish and restore the test failure.
				if err := os.Chmod(sourceDirectory, 0o700); err != nil {
					t.Errorf("✗ restore source permissions: %v", err)
				}
			})

			if err := os.Remove(source); !errors.Is(err, os.ErrPermission) {
				t.Fatalf("💣 source-removal fixture was not denied: %v", err)
			}

			destination := t.TempDir()

			stem := "boat"
			if sidecarFailure {
				stem = strings.Repeat("s", 253)
				if _, err := os.Stat(filepath.Join(destination, stem+".md")); !errors.Is(err, syscall.ENAMETOOLONG) {
					t.Fatalf("💣 sidecar fixture does not exceed the filename limit: %v", err)
				}
			}

			result := generation.Result{Artifacts: []artifact.Media{{TmpPath: source, FileExt: ".x"}}, Thoughts: []string{"generation notes"}}
			run := &generation.Generation{ProvModelPair: catalog.ProvModelPair{Model: catalog.Model{ID: "model", Media: media.Image}}, Preparation: generation.Preparation{Params: params.Values{params.FlagTypeThoughts: true}}}
			outcome := &output.GenerationOutcome{}

			_, savedMedia, err := writeRunResults(&result, destination, stem, "", run, nil, outcome)
			if !errors.Is(err, os.ErrPermission) || len(savedMedia) != 1 || savedMedia[0].Path != filepath.Join(destination, stem+".x") {
				t.Errorf("✗ cleanup failure or media-only completed facts lost: %+v, %v", savedMedia, err)
			}

			// #nosec G304 -- this path belongs to the test temporary directory.
			content, readErr := os.ReadFile(filepath.Join(destination, stem+".x"))
			if readErr != nil || string(content) != "generated bytes" {
				t.Errorf("✗ completed media changed: %q, %v", content, readErr)
			}

			if sidecarFailure {
				if !errors.Is(err, syscall.ENAMETOOLONG) || len(outcome.Artifacts) != 1 {
					t.Errorf("✗ sidecar not attempted or falsely reported: %+v, %v", outcome.Artifacts, err)
				}
			} else {
				sidecarPath := filepath.Join(destination, stem+".md")

				// #nosec G304 -- this path belongs to the test temporary directory.
				sidecarContent, sidecarErr := os.ReadFile(sidecarPath)
				if sidecarErr != nil || !strings.Contains(string(sidecarContent), "generation notes") {
					t.Errorf("✗ requested sidecar missing its content after cleanup failure: %q, %v", sidecarContent, sidecarErr)
				}

				if len(outcome.Artifacts) != 2 || outcome.Artifacts[1].Path != sidecarPath || outcome.Artifacts[1].Bytes != int64(len(sidecarContent)) {
					t.Errorf("✗ successfully closed sidecar absent from reported facts: %+v", outcome.Artifacts)
				}
			}

			if !t.Failed() {
				t.Log("✓ sidecar attempt and completed facts survive source cleanup failure")
			}
		})
	}

	if !t.Failed() {
		t.Log("✓ sidecar success and failure preserve the completed generation facts")
	}
}

// TestFailedPreparationRecord verifies invariant #3: Failed preparation records.
// Test class: Expanded.
// Test layer: Hardening/adversarial.
// What is being tested:
// Given an incompatible Veo reuse record, adjustRequest must return errs.ErrReuseVideoModel and
// leave recorded provider calls and responses empty. With no supplied parameters, the failed record
// must omit adjusted parameters. With resolution 720p supplied, the recorded adjusted parameters
// must retain that value.
func TestFailedPreparationRecord(t *testing.T) {
	loadedCatalog := shippedCatalog(t)

	modelPairs, err := loadedCatalog.ResolveModelInput("google/veo-3.1-fast-generate-preview")
	if err != nil || len(modelPairs) != 1 {
		t.Fatalf("💣 resolve Veo fixture: %v", err)
	}

	generator, err := newGenerator(loadedCatalog, "google", providerRegistrations())
	if err != nil {
		t.Fatalf("💣 construct Google fixture: %v", err)
	}

	for _, resolutionSupplied := range []bool{false, true} {
		inputs := params.FlagInputs{}
		if resolutionSupplied {
			inputs[params.FlagTypeResolution] = "720p"
		}

		sourceRecord := &metadata.Record{Provider: "google", Model: "veo-3.1-fast-generate-preview", Request: metadata.Request{Adjusted: json.RawMessage(`{"aspect-ratio":"1:1"}`)}}
		failedRecord := &metadata.Record{Model: modelPairs[0].Model.ID}
		outcome := &output.GenerationOutcome{}

		_, err := adjustRequest(generator, &modelPairs[0], inputs, nil, nil, loadedCatalog.Flags, outcome, failedRecord, &metadata.Reuse{Record: sourceRecord})
		if !errors.Is(err, errs.ErrReuseVideoModel) || len(failedRecord.Request.Calls) != 0 || len(failedRecord.Responses) != 0 {
			t.Errorf("✗ incompatible source was not rejected before submission: %v", err)
		}

		if !resolutionSupplied && len(failedRecord.Request.Adjusted) != 0 {
			t.Errorf("✗ failed record invents prepared parameters: %s", failedRecord.Request.Adjusted)
		}

		if resolutionSupplied {
			var adjusted map[string]any
			if err := json.Unmarshal(failedRecord.Request.Adjusted, &adjusted); err != nil || adjusted["resolution"] != "720p" {
				t.Errorf("✗ completed resolution was lost after rejection: %s, %v", failedRecord.Request.Adjusted, err)
			}
		}
	}

	if !t.Failed() {
		t.Log("✓ failed preparation records retain completed facts without inventing them")
	}
}
