// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package bfl

// The internal/provider/bfl section of the copy catalog, one constant per entry.
const (
	ImageGotTimed            = "BFL image request received timed input"
	ImageGotVideo            = "BFL image request received video input"
	KeyframePositionConflict = "keyframe %d time %g conflicts with position %g"
	KeyframeTimeForm         = "keyframe # %d, at %g seconds, is out of order or range"
	KeyframesNeedDuration    = "timed BFL keyframes require duration"
	PollURLMissing           = "%s: no polling_url in the submit response"
	SingleInputOnly          = "%s accepts one input"
	VideoContinuationTimed   = "BFL video continuation cannot be timed"
	VideoMediaMixed          = "BFL video request mixes image and video inputs"
	VideoOneContinuation     = "BFL video continuation accepts one video"
)
