#!/usr/bin/env python3
"""Generate model-roster.json from the embedded provider configs.

Run with Python 3 from the repository root after changing provider configs.
This script writes only scripts/invariants/model-roster.json; it does not
generate or update the manually maintained roster.md research document.

The provider configs are the authoritative declaration of provider and model
support: the shared configs under internal/provider/config, and each provider
package's own config directory (internal/provider/<package>/config). Adding a
provider means adding its package and config; this script discovers configs by
traversing those directories, so a new provider appears in the roster with no
script change.

The roster (scripts/invariants/model-roster.json) is a generated
consolidation for documentation and review. It is never edited by hand and
never a second source of truth: on any config change, regenerate it here.

Every entry states declared values under a key naming what the value governs:
the accepted value set, the numeric bounds, the size limits, the image count.
A null value means the configs declare no limit for that key. The script
composes no sentences — a model rule's statement is the config's own text,
carried through verbatim.

Usage:
  roster-gen.py            regenerate model-roster.json (reports changed/unchanged)
  roster-gen.py --check    exit 0 when the roster matches the configs, 2 when it
                           is stale or missing (nothing is written)

The "lastUpdated" field records the date the generated content last changed;
a regeneration that produces identical content keeps the existing date, so
re-running the script never dirties the file.
"""

import datetime
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PROVIDER_DIR = REPO / "internal" / "provider"
ROSTER_PATH = REPO / "scripts" / "invariants" / "model-roster.json"

# The parameter flags each roster section covers. The sizing trio and the input media and duration
# have their own sections; all other consumed flags are listed under "other parameters".
SIZING_FLAGS = {"size", "aspect-ratio", "resolution"}
SPLIT_FLAGS = ("aspect-ratio", "resolution")
INPUT_MEDIA_FLAG = "input-media"
DURATION_FLAG = "duration"

SCRIPT_REL = str(Path(__file__).resolve().relative_to(REPO))

ABOUT = "Autogenerated from the embedded provider configs — do not edit manually; regenerate with the generation script after any config change. A null value means the configs declare no limit."


def fail(msg):
    print(f"roster-gen: {msg}", file=sys.stderr)
    sys.exit(2)


def discover_configs():
    """Find every provider config by traversal: the shared config directory,
    then each provider package's own config directory. Returns decoded configs
    keyed by provider id, with basic identity validation."""
    paths = sorted(PROVIDER_DIR.glob("config/*.json")) + sorted(PROVIDER_DIR.glob("*/config/*.json"))
    if not paths:
        fail(f"no provider configs found under {PROVIDER_DIR}")
    configs = {}
    for path in paths:
        try:
            cfg = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as decode_err:
            fail(f"{path}: {decode_err}")
        pid = cfg.get("id")
        if not pid or not cfg.get("displayName") or not cfg.get("apiKeyEnvVar"):
            fail(f"{path}: provider identity incomplete")
        if pid in configs:
            fail(f"duplicate provider id {pid!r} ({path})")
        if not cfg.get("models"):
            fail(f"{path}: no models declared")
        configs[pid] = cfg
    return dict(sorted(configs.items()))


def param(model, flag_id):
    for p in model.get("params") or []:
        if p.get("flagID") == flag_id:
            return p
    return None


def fmt_num(x):
    if isinstance(x, float) and x.is_integer():
        return str(int(x))
    return str(x)


def size_limits(bounds):
    """The declared --size limits of one free-form model, each under the key
    naming what it limits; a limit the config leaves out is absent here."""
    limits = {}
    for key, field in (
        ("minimum pixels per edge", "minEdge"),
        ("maximum pixels per edge", "maxEdge"),
        ("pixels per edge divisible by", "edgeIncrem"),
        ("minimum total pixels", "minPx"),
        ("maximum total pixels", "maxPx"),
    ):
        if bounds.get(field):
            limits[key] = bounds[field]
    if bounds.get("maxRatio"):
        limits["maximum aspect ratio"] = fmt_num(bounds["maxRatio"]) + ":1"
    if bounds.get("longEdge"):
        limits["default long edge pixels"] = bounds["longEdge"]
    return limits


def param_values(entry):
    """One parameter's declared acceptance: its closed value set, or its
    numeric bounds, or a null value set where the config declares neither."""
    if entry.get("allowedValues"):
        return {"values": entry["allowedValues"]}
    bounds = {}
    for key, field in (("minimum", "minValue"), ("maximum", "maxValue")):
        if entry.get(field) is not None:
            bounds[key] = entry[field]
    return bounds or {"values": None}


def under_flag(flag_id, record):
    """The record's keys named for the flag they belong to, so one entry can
    carry two flags' acceptance side by side."""
    return {f"{flag_id} {key}": value for key, value in record.items()}


def must_resize(cfg):
    return bool(((cfg.get("config") or {}).get("videoAPI") or {}).get("inputMediaMustResize"))


def input_media_constraints(cfg, model):
    """One model's input-media acceptance: how many images it takes — zero
    where it consumes none, null where the config caps none — and, where the
    provider's API demands it, that the kept images are resized to the
    request size."""
    entry = param(model, INPUT_MEDIA_FLAG)
    if entry is None:
        return {"maximum images": 0}
    record = {"maximum images": entry.get("maxMultiple") or None}
    if model.get("media") == "video" and must_resize(cfg):
        record["resized to request size"] = True
    return record


class Grouper:
    """Collects (model, signature) pairs and emits grouped entries in
    first-appearance order. Grouping is per provider — an explicit model list
    never mixes providers — except that parts covering every model of their
    provider (of one media, or of all) compress to a provider scope, and
    same-signature provider scopes of the same media merge across providers."""

    def __init__(self, configs):
        self.configs = configs
        self.order = []
        self.members = {}

    def add(self, pid, model_id, signature):
        part_key = (pid, signature)
        if part_key not in self.members:
            self.members[part_key] = []
            self.order.append(part_key)
        self.members[part_key].append(model_id)

    def provider_models(self, pid, media=None):
        return [m["id"] for m in self.configs[pid]["models"] if media in (None, m["media"])]

    def complete_scope(self, pid, model_ids):
        """The media scope over which model_ids is every model the provider
        declares: None-scope (all), one media, or no completeness ("partial")."""
        for media in (None, "image", "video"):
            if sorted(model_ids) == sorted(self.provider_models(pid, media)):
                return media
        return "partial"

    def entries(self, value_key=None):
        """The grouped entries, each carrying its model or provider scope and
        then its values: merged in as their own keys, or held under value_key
        where one is given."""
        merged = {}  # (signature, scope) -> providers, for provider-complete parts
        out = []
        for pid, signature in self.order:
            model_ids = self.members[(pid, signature)]
            scope = self.complete_scope(pid, model_ids)
            if scope == "partial":
                out.append(({"models": model_ids}, signature))
                continue
            merge_key = (signature, scope)
            if merge_key in merged:
                merged[merge_key]["providers"].append(pid)
                continue
            entry = {"providers": [pid], **({"media": scope} if scope else {})}
            merged[merge_key] = entry
            out.append((entry, signature))
        result = []
        for entry, signature in out:
            values = json.loads(signature)
            if value_key is None:
                entry.update(values)
            else:
                entry[value_key] = values
            result.append(entry)
        return result


# Consolidate declared provider capabilities and reject duplicate aliases.
def build(configs):
    providers = [
        {"provider": cfg["displayName"], "id": pid, "API key variable": cfg["apiKeyEnvVar"]}
        for pid, cfg in configs.items()
    ]

    models = {}
    aliases = {}
    for pid, cfg in configs.items():
        models[pid] = {
            "image": [m["id"] for m in cfg["models"] if m["media"] == "image"],
            "video": [m["id"] for m in cfg["models"] if m["media"] == "video"],
        }
        for m in cfg["models"]:
            for alias in m.get("aliases") or []:
                if alias in aliases:
                    fail(f"alias {alias!r} declared twice")
                aliases[alias] = f"{pid}/{m['id']}"

    images = Grouper(configs)
    free_form, fixed = Grouper(configs), Grouper(configs)
    split = Grouper(configs)
    duration = Grouper(configs)
    other = {}  # flag id -> Grouper
    rules = Grouper(configs)

    for pid, cfg in configs.items():
        for m in cfg["models"]:
            mid = m["id"]
            images.add(pid, mid, json.dumps(input_media_constraints(cfg, m)))

            size_entry = param(m, "size")
            if size_entry is not None and size_entry.get("customSize"):
                free_form.add(pid, mid, json.dumps(size_limits(size_entry["customSize"])))
            elif size_entry is not None and size_entry.get("allowedValues"):
                fixed.add(pid, mid, json.dumps(size_entry["allowedValues"]))
            else:
                shape = {}
                for flag in SPLIT_FLAGS:
                    entry = param(m, flag)
                    if entry is not None:
                        shape.update(under_flag(flag, param_values(entry)))
                if shape:
                    split.add(pid, mid, json.dumps(shape))

            duration_entry = param(m, DURATION_FLAG)
            if duration_entry is not None:
                duration.add(pid, mid, json.dumps(param_values(duration_entry)))

            for p in m.get("params") or []:
                flag = p.get("flagID")
                if flag in SIZING_FLAGS or flag in (INPUT_MEDIA_FLAG, DURATION_FLAG):
                    continue
                other.setdefault(flag, Grouper(configs)).add(pid, mid, json.dumps(param_values(p)))

            for p in m.get("params") or []:
                if p.get("ruleDescription"):
                    rules.add(pid, mid, json.dumps({"parameter": "--" + p["flagID"], "statement": p["ruleDescription"]}))

    other_entries = []
    for flag in sorted(other):
        for entry in other[flag].entries():
            other_entries.append({"parameter": "--" + flag, **entry})

    rule_entries = []
    for entry in rules.entries("rule"):
        rule = entry.pop("rule")
        rule_entries.append({"parameter": rule["parameter"], **entry, "statement": rule["statement"]})

    return {
        "title": "Model Roster",
        "filename": ROSTER_PATH.name,
        "generation-script": SCRIPT_REL,
        "lastUpdated": None,  # settled against the existing file before writing
        "about": ABOUT,
        "providers": providers,
        "models": models,
        "aliases": aliases,
        "input media": images.entries(),
        "sizing": {
            "free-form bounds": free_form.entries(),
            "fixed sizes": fixed.entries("sizes"),
            "separate aspect and resolution": split.entries(),
        },
        "duration": duration.entries(),
        "other parameters": other_entries,
        "model rules": rule_entries,
    }


def content_without_date(roster):
    return {k: v for k, v in roster.items() if k != "lastUpdated"}


# Check or rewrite the roster, retaining its date when capability data is unchanged.
def main():
    check_only = sys.argv[1:] == ["--check"]
    if sys.argv[1:] not in ([], ["--check"]):
        fail(f"unknown arguments {sys.argv[1:]}; usage: roster-gen.py [--check]")

    roster = build(discover_configs())

    existing = None
    if ROSTER_PATH.exists():
        try:
            existing = json.loads(ROSTER_PATH.read_text(encoding="utf-8"))
        except json.JSONDecodeError as decode_err:
            if check_only:
                fail(f"{ROSTER_PATH.name} does not parse: {decode_err}")
            existing = None

    kept_date = existing.get("lastUpdated") if existing is not None else None
    unchanged = existing is not None and content_without_date(existing) == content_without_date(roster)

    if check_only:
        if existing is None:
            fail(f"{ROSTER_PATH.name} is missing")
        if not unchanged:
            fail(f"{ROSTER_PATH.name} is stale: regenerate with scripts/roster-gen.py")
        print(f"roster-gen: {ROSTER_PATH.name} matches the provider configs")
        return

    if unchanged:
        roster["lastUpdated"] = kept_date
        print(f"roster-gen: {ROSTER_PATH.name} already current (lastUpdated {roster['lastUpdated']})")
    else:
        roster["lastUpdated"] = datetime.date.today().isoformat()
        print(f"roster-gen: {ROSTER_PATH.name} regenerated (lastUpdated {roster['lastUpdated']})")
    ROSTER_PATH.write_text(json.dumps(roster, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
