// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package errs

// The internal/errs section of the copy catalog, one constant per entry.
const (
	APIKeyMissingForm = "%s %s (config key: api-keys.%s in ~/.bildomat/config.yml)"
	StatusContextForm = "%s: status %v"
)
