// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package metadata

// The internal/metadata section of the copy catalog, one constant per entry.
const (
	BinarySaved       = "[Bildomat: base64 data redacted for length; saved locally to %s]"
	BinaryUnavailable = "[Bildomat: base64 data unavailable; see persistence-errors]"
)
