// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package provider

// The internal/provider section of the copy catalog, one constant per entry.
const (
	APISectionMissing         = "%s.json: no %s for the resolved medium"
	DownloadURLMissing        = "%s: %s: no download url in the completed poll"
	FieldContextForm          = "field %s"
	FrameFieldUnavailable     = "a frame prefix reached a request with no frame field"
	FrameMediaUndescribed     = "provider has no frame-media request description"
	FrameRoleDuplicate        = "duplicate frame role %s"
	FrameTimeUnresolved       = "unresolved frame time on %s"
	JSONMediaPartsUnsupported = "JSON requests cannot contain multipart file parts"
	JobDecodeErrorForm        = "jobID %q: %w"
	MissingResponseValue      = "missing"
	RespEntryForm             = "%s: entry %d"
	SingleMediaNoVideo        = "single-or-array request does not accept video"
	StartContextForm          = "%s start"
	UnknownStatusForm         = "%s (%s): %s"
)
