// Code generated by copygen from internal/templates/copy.toml. DO NOT EDIT.

package params

// The internal/params section of the copy catalog, one constant per entry.
const (
	BoundMaxForm            = "max %s"
	BoundMinForm            = "min %s"
	BoundsAndValuesConflict = "size bounds and allowed values both declared"
	NegativeMaxMultipleForm = "negative maxMultiple %d"
	RangeBoundNegative      = "negative range bound"
	RangeInverted           = "minValue %s exceeds maxValue %s"
	ReasonModelLimits       = "%s limits"
	ReasonSupersededBySize  = "superseded by Size %s"
	ValuesAndRangeConflict  = "allowed values and a range both declared"
)
